[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.18", "ninja"]
build-backend = "setuptools.build_meta"

[project]
name = "spherical_harmonics"
version = "0.1.0"
description = "Spherical Harmonics Library"
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.20",
]